Donggrina/Frontend

han.ts

test: git flow test

---

kyung.ts

git flow test

---

kyung.ts

[#13] test

---

components/common/Input/Input.module.scss
components/common/Input/index.tsx
package-lock.json
package.json
pages/input-test/index.tsx
styles/globals.css
tsconfig.json

> #21 
> 시안 나와있는 input 디자인 참고해서 input 공통 컴포넌트 만들었습니다.
> input-test 페이지에서 확인 가능합니다.
> error처리 부분 맞게 작성한건지 확인 부탁드립니다....!

Feat: input 공통 컴포넌트 구현

---

.github/workflows/main.yml

- github action을 활용해 pull request 발생시 디스코드로 알림 구현

Chore: create main.yml

---

.github/workflows/test-every-push.yml

- github actions을 활용해 모든 push 마다 npm i, lint, tsc, build 검사

Chore: 모든 push 마다 npm i, lint, tsc, build 검사

---

components/common/Input/index.tsx

fix: type error 수정

---

components/common/Header/Header.module.scss
styles/globals.css

> #22 
- 중앙 정렬 맞추기
- global style padding 수정
>

Fix: header 디자인 수정

---

components/common/Input/index.tsx
components/common/Label/index.tsx
pages/input-test/index.module.scss
pages/input-test/index.tsx

> #21
> input이랑 label 분리해서 조합해서 쓰기 편하게 바꿨습니다!
> 맞는 방법으로 한건지 모르겠네요.. 확인 부탁드립니다..!

Refactor: input, label 컴포넌트 분리

---

pages/_app.tsx

> #22 
> isHeader -> IsHeader.ts 로 파일 이름 변경
>

Fix: 파일명 수정

---

components/common/Form/index.tsx
components/common/Input/input-type.ts
components/common/select/drop-down/drop-down.module.scss
components/common/select/drop-down/index.tsx
components/common/select/index.tsx
components/common/select/select.module.scss
hooks/use-close-dropdown.tsx
package-lock.json
package.json
pages/test/input-test/index.tsx
pages/test/select-test/index.tsx
public/images/select/dropdown-down.svg
public/images/select/dropdown-up.svg

#55 
- select 디자인
- dropdown 컴포넌트 개발
- esc 키 눌렀을 때, select 부분 클릭했을 때 dropdown이 닫히는 훅 (useCloseDropDown) 구현
- react-hook-form : useController, useFornContext를 사용해 내부 컴포넌트에서 폼필드로 데이터를 공유할 수 있도록 구현
>

Feat: Select input 구현 완료

---

components/common/Form/Form.module.scss
components/common/Form/index.tsx
components/common/Input/date-input/index.tsx
components/common/Input/input-type.ts
components/common/Input/main-input/index.tsx
components/common/Input/main-input/main-input.module.scss
components/common/Input/mixins.scss
components/common/Input/weight-input/index.tsx
components/common/Label/index.tsx
components/common/Label/label.module.scss
components/common/select/drop-down/drop-down.module.scss
components/common/select/drop-down/index.tsx
components/common/select/index.tsx
components/common/select/select.module.scss
hooks/use-close-dropdown.tsx
package-lock.json
package.json
pages/test/input-test/index.tsx
pages/test/select-test/index.tsx
public/images/select/dropdown-down.svg
public/images/select/dropdown-up.svg

#67 
- 라벨 컴포넌트 분리
- 라벨 컴포넌트 디자인 수정
- Weight input validate 설정 : 0.01kg보다 작거나 100kg보다 크면 에러 문구 출력
>

Feat: label 컴포넌트 구현

---

components/common/radio/context/radio-context.tsx
components/common/radio/radio-input/radio-input.tsx
components/common/radio/radio-label/radio-label.tsx
components/common/radio/radio.tsx
pages/test/radio-test/index.tsx

#71 
- radio 컴포넌트를 제어 컴포넌트로 개발했기 때문에 리팩토링 했습니다.
- radio 컴포넌트는 options, control, name 값을 받습니다.
- options는 value, text, id 값을 포함해야합니다.
>

Refactor: radio 컴포넌트 리팩토링

---

components/common/Form/index.tsx
components/common/Input/date-input/index.tsx
components/common/Input/input-type.ts
components/common/Input/main-input/index.tsx
components/common/Input/weight-input/index.tsx
components/common/select/index.tsx
pages/test/input-test/index.tsx

#67 
- 컴파운드 패턴 활용해서 라벨 컴포넌트 분리 
>

Refactor: 라벨 컴포넌트 컴파운드 패턴 활용해 분리

---

components/calendar-compound/calendar.tsx
components/calendar-compound/calendar.type.ts
components/calendar-compound/components/weekly/calendar-weekly.tsx
components/calendar-compound/components/year/calendar-year.module.scss
components/calendar-compound/components/year/calendar-year.tsx
utils/date/date.utils.ts

#78 
- 캘린더 연도 기능 추가. (현재 연도 기준 -1, +1)
- 슬라이더 기능 추가.
- 셀렉트 기능 추가.
>

Feat: 연도 기능 추가

---

components/kebab/kebab.module.scss
components/kebab/kebab.tsx
hooks/use-toggle.ts

#90 
위치가 달라질 수 있어요. 그럴 때에는 클래스를 만들어 추가해야합니다.
>

Fix: 팝오버 위치 오류

---

components/calendar-compound/calendar.tsx
components/calendar-compound/components/weekly/calendar-weekly.tsx
package-lock.json
package.json
pages/test/calendar/index.tsx
store/calendar.store.ts
store/utils/index.ts
utils/date/date.utils.ts

#97 
- Zustand 패키지 설치
- calendar.store.ts 추가.
- Zustand Selector 함수 추가.
test/calender에서 사용방법을 확인해보세요!
>

Feat: 캘린더 전역상태 추가.

---

api/my/groups/index.ts
components/start-family/link-list/link-list.tsx
pages/start-family/register-code/index.module.scss
pages/start-family/register-code/index.tsx

#112 
- 가족 코드 등록 페이지 구현했습니다.
- 가족 코드와 닉네임 입력 시 가입이 완료됩니다.
- 가족 생성 페이지 코드를 수정했습니다.
>

Feat: 가족 코드 등록 페이지 구현

---

api/index.ts

Fix: Rt 인터셉터 수정

---

components/calendar-monthly/time-scroller.tsx

#44 
일정 등록 시 시간 설정하는 컴포넌트에서 터치패드로 스크롤 할 때 속도가 너무 빠른 문제 수정
wheel event deltaY 값, scrollTop 값 변경

Fix: 일정 등록 시계 스크롤 속도 수정

---

components/calendar-monthly/calendar-todo-post-success.tsx
components/common/button/button.tsx
components/common/modal/modal.module.scss
components/mypage/family/family-list-item/delete-member-modal/delete-member-modal.tsx
components/mypage/family/family-util-buttons/family-delete-button/delete-modal/delete-modal.tsx
components/mypage/family/family-util-buttons/family-delete-button/family-delete-button.tsx
components/mypage/family/family-util-buttons/family-rename-button/rename-modal/rename-modal.tsx
components/start-pet/finish/share-modal/share-modal.tsx
config/index.ts
pages/growth/create/complete-modal/index.tsx

#137 
- 모달, 버튼 스타일 수정했습니다.
- 구글 로그인 추가했습니다.
- round가 필요한 부분에 leftRound, rightRound를 추가하시면 됩니다.
>

Refactor: 모달, 버튼 수정 및 구글 로그인 추가

---

styles/color.css

Feat: 스켈레톤 ui 폴더 구조 셋팅

---

api/diaries/index.ts
components/diaries/diary-content/content-image/content-image.module.scss
components/diaries/diary-content/content-image/index.tsx
components/diaries/diary-content/diary-content.module.scss
components/diaries/diary-content/diary-content.tsx
components/diaries/diary-content/kebab/index.tsx
components/diaries/diary-content/kebab/kebab.module.scss
components/diaries/diary-create/diary-create.module.scss
components/diaries/diary-create/diary-create.tsx
components/diaries/pet-checkbox.module.scss
components/diaries/pet-checkbox.tsx
components/diaries/pet-select.module.scss
components/diaries/pet-select.tsx
pages/diaries/create/index.tsx
pages/diaries/index.tsx
utils/constants/nav-data.ts

Feat: 다이어리 등록페이지

---

api/calendar/request.ts
api/calendar/request.type.ts
api/search/index.ts
api/search/index.type.ts
components/calendar-monthly/calendar-todo.tsx
components/calendar-monthly/time-scroller.tsx
components/search/search-filter.tsx
components/search/search-form.module.scss
components/search/search-form.tsx
components/search/search-pet-checkbox.tsx
hooks/queries/search/use-results-query.ts
pages/calendar/[calendarId]/index.tsx
pages/calendar/search/index.tsx
pages/calendar/search/search.module.scss
pages/diaries/search/index.tsx
pages/diaries/search/search.module.scss
pages/family/search/index.tsx
pages/family/search/search.module.scss
pages/growth/search/index.tsx
pages/growth/search/search.module.scss
types/search/index.ts
utils/constants/search.ts

#44
일정 등록할 때 시간 클릭으로 선택할 수 있도록 기능 추가
검색 페이지 커밋들 develop으로 머지 (이전에 main으로 머지됐어요..)

Feat: 시계 스크롤러 클릭으로 선택 기능 추가

---

pages/_app.tsx
utils/is-nav.ts

#159 
- nav를 사용하는 곳이 디자인상 많지 않기 때문에 수정하였습니다.
>

Fix: nav 로직 수정

---

components/calendar-monthly/calendar-todo-post-success.module.scss
components/calendar-monthly/calendar-todo-profile.module.scss
pages/calendar/[calendarId]/calendar-id.module.scss
pages/calendar/create/create.module.scss
pages/calendar/create/index.tsx
pages/calendar/index.tsx
pages/calendar/search/search.module.scss
pages/diaries/[diaryId]/diary-id.module.scss
pages/diaries/search/search.module.scss
pages/growth/search/search.module.scss

#44 #115 
검색페이지, 일정, 다이어리 등 좌우 여백, 하단 여백 수정
일정 등록 완료 모달 닫힘 방지 / 모달 열린 채로 중복 등록 방지

Fix: 페이지별 ui 수정

---

components/calendar-monthly/calendar-todo-profile.module.scss
components/common/Header/main-header/index.tsx
components/growth/profile/profile.module.scss
pages/growth/[growthId]/growth-detail.module.scss

Fix: 마이페이지 이동 에러 수정

---

components/diaries/jihye/diary-edit-memo/diary-edit-memo.module.scss
components/diaries/jihye/diary-edit-memo/index.tsx
pages/growth/create/create.module.scss
pages/growth/create/index.tsx

- memo component 분리
- 타입 제네릭으로 설정 
>

Feat: memo component 분리 및 구현

---

components/diaries/edit/diary-edit-hanbin/diary-calendar-modal/diary-calendar-modal.module.scss
components/diaries/edit/diary-edit-hanbin/diary-calendar-modal/index.tsx
components/diaries/edit/diary-edit-hanbin/diary-edit-hanbin.module.scss
components/diaries/edit/diary-edit-hanbin/index.tsx
pages/diaries/[diaryId]/edit/index.tsx

#65 
다이어리 수정 페이지 날짜 선택 시 달력 모달을 띄웁니다.

Feat: 다이어리 수정 페이지 날짜 선택 모달 구현

---

components/calendar-monthly/calendar-todo.module.scss
pages/calendar/[calendarId]/index.tsx

Fix: 일정 상세 시각, 검색 결과 등 수정
